import { Member } from './types';

export const mockMembers: Member[] = [
  {
    id: '1',
    username: 'nguyenvana',
    profilePicture: 'https://i.pravatar.cc/150?img=1',
    bio: 'Full-stack developer passionate about React and Node.js',
    github: 'nguyenvana',
    showGithub: true,
    createdAt: '2024-01-15T00:00:00Z',
    role: 'ADMIN',
    stats: {
      totalQuestions: 45,
      totalAnswers: 128,
      totalUpvotes: 890,
      chosenAnswers: 35,
      totalViews: 12500,
      reputation: 1250,
    },
  },
  {
    id: '2',
    username: 'tranvanbao',
    profilePicture: 'https://i.pravatar.cc/150?img=2',
    bio: 'Frontend enthusiast, love creating beautiful UIs',
    github: 'tranvanbao',
    showGithub: true,
    createdAt: '2024-02-20T00:00:00Z',
    role: 'MEMBER',
    stats: {
      totalQuestions: 32,
      totalAnswers: 95,
      totalUpvotes: 720,
      chosenAnswers: 28,
      totalViews: 9800,
      reputation: 980,
    },
  },
  {
    id: '3',
    username: 'lethicamly',
    profilePicture: 'https://i.pravatar.cc/150?img=3',
    bio: 'Backend developer specializing in microservices',
    showGithub: false,
    createdAt: '2024-03-10T00:00:00Z',
    role: 'MEMBER',
    stats: {
      totalQuestions: 28,
      totalAnswers: 87,
      totalUpvotes: 650,
      chosenAnswers: 22,
      totalViews: 8200,
      reputation: 850,
    },
  },
  {
    id: '4',
    username: 'phamquangduc',
    profilePicture: 'https://i.pravatar.cc/150?img=4',
    bio: 'DevOps engineer and cloud architect',
    github: 'phamquangduc',
    showGithub: true,
    createdAt: '2024-01-25T00:00:00Z',
    role: 'MEMBER',
    stats: {
      totalQuestions: 38,
      totalAnswers: 76,
      totalUpvotes: 580,
      chosenAnswers: 18,
      totalViews: 7100,
      reputation: 720,
    },
  },
  {
    id: '5',
    username: 'hoangminhdang',
    profilePicture: 'https://i.pravatar.cc/150?img=5',
    bio: 'Mobile app developer (React Native & Flutter)',
    github: 'hoangminhdang',
    showGithub: true,
    createdAt: '2024-04-05T00:00:00Z',
    role: 'MEMBER',
    stats: {
      totalQuestions: 22,
      totalAnswers: 65,
      totalUpvotes: 480,
      chosenAnswers: 15,
      totalViews: 6200,
      reputation: 620,
    },
  },
  {
    id: '6',
    username: 'vothithanh',
    profilePicture: 'https://i.pravatar.cc/150?img=6',
    bio: 'UI/UX Designer with development skills',
    github: 'vothithanh',
    showGithub: true,
    createdAt: '2024-03-15T00:00:00Z',
    role: 'MEMBER',
    stats: {
      totalQuestions: 18,
      totalAnswers: 42,
      totalUpvotes: 380,
      chosenAnswers: 12,
      totalViews: 4500,
      reputation: 450,
    },
  },
  {
    id: '7',
    username: 'doancongminh',
    profilePicture: 'https://i.pravatar.cc/150?img=7',
    bio: 'Data scientist and ML engineer',
    github: 'doancongminh',
    showGithub: true,
    createdAt: '2024-04-20T00:00:00Z',
    role: 'MEMBER',
    stats: {
      totalQuestions: 35,
      totalAnswers: 58,
      totalUpvotes: 420,
      chosenAnswers: 16,
      totalViews: 5800,
      reputation: 580,
    },
  },
  {
    id: '8',
    username: 'nguyenthimai',
    profilePicture: 'https://i.pravatar.cc/150?img=8',
    bio: 'Quality assurance engineer',
    showGithub: false,
    createdAt: '2024-05-10T00:00:00Z',
    role: 'MEMBER',
    stats: {
      totalQuestions: 15,
      totalAnswers: 38,
      totalUpvotes: 280,
      chosenAnswers: 8,
      totalViews: 3200,
      reputation: 320,
    },
  },
];
