import { MockResults } from './types';

export const mockResults: MockResults = {
  questions: [
    {
      id: '1',
      title: 'How to implement authentication in React?',
      content:
        'I need help with implementing JWT authentication in my React application...',
      author: 'john_dev',
      views: 245,
      upvotes: 15,
      answers: 3,
      isSolved: true,
      tags: ['React', 'Authentication', 'JWT'],
      createdAt: '2 hours ago',
    },
    {
      id: '2',
      title: 'Best practices for database design?',
      content:
        'What are the key principles I should follow when designing a database schema...',
      author: 'db_expert',
      views: 189,
      upvotes: 22,
      answers: 7,
      isSolved: false,
      tags: ['Database', 'SQL', 'Design'],
      createdAt: '5 hours ago',
    },
    {
      id: '3',
      title: 'Optimize performance in React apps',
      content: 'Looking to improve loading speed in large React projects...',
      author: 'react_master',
      views: 322,
      upvotes: 40,
      answers: 6,
      isSolved: true,
      tags: ['React', 'Performance'],
      createdAt: '1 day ago',
    },
    {
      id: '4',
      title: 'State management in Vue.js',
      content: 'How to effectively manage state in a medium-sized Vue.js app?',
      author: 'vue_wizard',
      views: 110,
      upvotes: 14,
      answers: 2,
      isSolved: false,
      tags: ['Vue.js', 'State'],
      createdAt: '3 days ago',
    },
    {
      id: '5',
      title: 'How to use TypeScript with Node.js',
      content:
        'I’m transitioning to TypeScript and need guidance using it in Node apps...',
      author: 'ts_fan',
      views: 205,
      upvotes: 19,
      answers: 4,
      isSolved: true,
      tags: ['Node.js', 'TypeScript'],
      createdAt: '4 days ago',
    },
    {
      id: '6',
      title: 'JavaScript async/await examples',
      content:
        'Could someone explain how async/await works in JavaScript with examples?',
      author: 'js_learner',
      views: 540,
      upvotes: 35,
      answers: 8,
      isSolved: true,
      tags: ['JavaScript', 'Async'],
      createdAt: '5 days ago',
    },
    {
      id: '7',
      title: 'How to deploy a React app to Vercel?',
      content: 'Need help with deploying my React project to Vercel...',
      author: 'frontend_deploy',
      views: 134,
      upvotes: 10,
      answers: 1,
      isSolved: false,
      tags: ['React', 'Deployment', 'Vercel'],
      createdAt: '6 hours ago',
    },
    {
      id: '8',
      title: 'Difference between SQL and NoSQL',
      content: 'Trying to understand when to use SQL vs NoSQL...',
      author: 'db_novice',
      views: 308,
      upvotes: 26,
      answers: 5,
      isSolved: false,
      tags: ['SQL', 'NoSQL'],
      createdAt: '8 hours ago',
    },
    {
      id: '9',
      title: 'Build a REST API with Express',
      content: 'How to create a basic REST API using Express?',
      author: 'node_noob',
      views: 168,
      upvotes: 18,
      answers: 3,
      isSolved: true,
      tags: ['Express', 'Node.js'],
      createdAt: '12 hours ago',
    },
    {
      id: '10',
      title: 'CSS Grid vs Flexbox',
      content: 'When should I use CSS Grid over Flexbox?',
      author: 'css_mania',
      views: 450,
      upvotes: 29,
      answers: 4,
      isSolved: true,
      tags: ['CSS', 'Grid', 'Flexbox'],
      createdAt: '2 days ago',
    },
    {
      id: '11',
      title: 'How to use Prisma with PostgreSQL?',
      content: 'I want to connect my app to PostgreSQL using Prisma...',
      author: 'orm_guy',
      views: 89,
      upvotes: 12,
      answers: 2,
      isSolved: false,
      tags: ['Prisma', 'PostgreSQL'],
      createdAt: '10 hours ago',
    },
    {
      id: '12',
      title: 'Using Redux Toolkit in React',
      content: 'What are the benefits of using Redux Toolkit?',
      author: 'react_reduxer',
      views: 198,
      upvotes: 21,
      answers: 5,
      isSolved: true,
      tags: ['React', 'Redux'],
      createdAt: '11 hours ago',
    },
    {
      id: '13',
      title: 'Firebase authentication setup',
      content: 'How do I integrate Firebase Auth in my app?',
      author: 'firebase_nerd',
      views: 222,
      upvotes: 17,
      answers: 4,
      isSolved: false,
      tags: ['Firebase', 'Authentication'],
      createdAt: '7 hours ago',
    },
    {
      id: '14',
      title: 'Why use useCallback in React?',
      content: 'What’s the real benefit of using useCallback?',
      author: 'react_master',
      views: 144,
      upvotes: 13,
      answers: 3,
      isSolved: true,
      tags: ['React', 'Hooks'],
      createdAt: '9 hours ago',
    },
    {
      id: '15',
      title: 'Integrating Stripe with Node.js',
      content: 'How to securely accept payments with Stripe in Node.js?',
      author: 'payment_guy',
      views: 176,
      upvotes: 20,
      answers: 5,
      isSolved: true,
      tags: ['Node.js', 'Stripe'],
      createdAt: '13 hours ago',
    },
    {
      id: '16',
      title: 'How to write unit tests in Jest?',
      content: 'Best practices for writing unit tests using Jest...',
      author: 'test_writer',
      views: 201,
      upvotes: 22,
      answers: 3,
      isSolved: false,
      tags: ['Testing', 'Jest'],
      createdAt: '14 hours ago',
    },
    {
      id: '17',
      title: 'GraphQL vs REST',
      content: 'Should I use GraphQL or REST for my API?',
      author: 'api_builder',
      views: 325,
      upvotes: 28,
      answers: 6,
      isSolved: false,
      tags: ['GraphQL', 'REST'],
      createdAt: '15 hours ago',
    },
    {
      id: '18',
      title: 'How to use Docker for local dev?',
      content: 'Can someone explain a simple dev setup using Docker?',
      author: 'docker_dev',
      views: 160,
      upvotes: 14,
      answers: 2,
      isSolved: false,
      tags: ['Docker', 'Development'],
      createdAt: '16 hours ago',
    },
    {
      id: '19',
      title: 'Set up Tailwind CSS in Next.js',
      content: 'Need help configuring Tailwind CSS with Next.js',
      author: 'next_tailwind',
      views: 147,
      upvotes: 11,
      answers: 3,
      isSolved: true,
      tags: ['Tailwind', 'Next.js'],
      createdAt: '17 hours ago',
    },
    {
      id: '20',
      title: 'Build dark mode in React app',
      content: 'How to toggle between dark/light themes in React?',
      author: 'theme_toggler',
      views: 188,
      upvotes: 25,
      answers: 4,
      isSolved: true,
      tags: ['React', 'DarkMode'],
      createdAt: '18 hours ago',
    },
  ],

  tags: [
    {
      id: '1',
      name: 'React',
      questionsCount: 142,
      description: 'A JavaScript library for building user interfaces',
    },
    {
      id: '2',
      name: 'JavaScript',
      questionsCount: 256,
      description: 'High-level programming language',
    },
    {
      id: '3',
      name: 'Node.js',
      questionsCount: 98,
      description: 'JavaScript runtime environment',
    },
    {
      id: '4',
      name: 'TypeScript',
      questionsCount: 130,
      description: 'Typed superset of JavaScript',
    },
    {
      id: '5',
      name: 'Vue.js',
      questionsCount: 85,
      description: 'Progressive JavaScript framework',
    },
    {
      id: '6',
      name: 'CSS',
      questionsCount: 192,
      description: 'Style sheet language for designing webpages',
    },
    {
      id: '7',
      name: 'HTML',
      questionsCount: 215,
      description: 'Standard markup language for documents',
    },
    {
      id: '8',
      name: 'SQL',
      questionsCount: 160,
      description: 'Structured Query Language for relational databases',
    },
    {
      id: '9',
      name: 'MongoDB',
      questionsCount: 97,
      description: 'Document-based NoSQL database',
    },
    {
      id: '10',
      name: 'Firebase',
      questionsCount: 110,
      description: 'Backend-as-a-Service platform by Google',
    },
    {
      id: '11',
      name: 'Express',
      questionsCount: 78,
      description: 'Minimalist web framework for Node.js',
    },
    {
      id: '12',
      name: 'Redux',
      questionsCount: 120,
      description: 'State management library for JavaScript apps',
    },
    {
      id: '13',
      name: 'PostgreSQL',
      questionsCount: 99,
      description: 'Advanced open-source relational database',
    },
    {
      id: '14',
      name: 'Tailwind',
      questionsCount: 76,
      description: 'Utility-first CSS framework',
    },
    {
      id: '15',
      name: 'Next.js',
      questionsCount: 112,
      description: 'React framework with server-side rendering',
    },
    {
      id: '16',
      name: 'GraphQL',
      questionsCount: 88,
      description: 'Query language for APIs',
    },
    {
      id: '17',
      name: 'Docker',
      questionsCount: 135,
      description: 'Platform for containerizing applications',
    },
    {
      id: '18',
      name: 'Prisma',
      questionsCount: 65,
      description: 'Next-gen ORM for Node.js and TypeScript',
    },
    {
      id: '19',
      name: 'Jest',
      questionsCount: 73,
      description: 'Testing framework for JavaScript',
    },
    {
      id: '20',
      name: 'Stripe',
      questionsCount: 50,
      description: 'Payment processing platform',
    },
  ],

  users: [
    {
      id: '1',
      username: 'john_dev',
      bio: 'Full-stack developer',
      questionsCount: 15,
      answersCount: 42,
      reputation: 1250,
    },
    {
      id: '2',
      username: 'react_master',
      bio: 'React specialist',
      questionsCount: 8,
      answersCount: 156,
      reputation: 2890,
    },
    {
      id: '3',
      username: 'db_expert',
      bio: 'Database architect',
      questionsCount: 23,
      answersCount: 78,
      reputation: 1840,
    },
    {
      id: '4',
      username: 'code_ninja',
      bio: 'JavaScript enthusiast',
      questionsCount: 19,
      answersCount: 90,
      reputation: 1375,
    },
    {
      id: '5',
      username: 'typescript_hero',
      bio: 'Type safety advocate',
      questionsCount: 7,
      answersCount: 104,
      reputation: 2120,
    },
    {
      id: '6',
      username: 'ui_guru',
      bio: 'Frontend designer',
      questionsCount: 12,
      answersCount: 56,
      reputation: 980,
    },
    {
      id: '7',
      username: 'mongo_mania',
      bio: 'NoSQL lover',
      questionsCount: 20,
      answersCount: 33,
      reputation: 890,
    },
    {
      id: '8',
      username: 'sql_master',
      bio: 'Data is everything',
      questionsCount: 14,
      answersCount: 97,
      reputation: 1760,
    },
    {
      id: '9',
      username: 'cloud_genius',
      bio: 'Cloud & DevOps expert',
      questionsCount: 5,
      answersCount: 75,
      reputation: 2015,
    },
    {
      id: '10',
      username: 'css_lover',
      bio: 'Making the web pretty',
      questionsCount: 16,
      answersCount: 43,
      reputation: 1120,
    },
    {
      id: '11',
      username: 'backend_boss',
      bio: 'Node.js & Express wizard',
      questionsCount: 11,
      answersCount: 102,
      reputation: 1895,
    },
    {
      id: '12',
      username: 'test_runner',
      bio: 'Automated testing fan',
      questionsCount: 6,
      answersCount: 58,
      reputation: 990,
    },
    {
      id: '13',
      username: 'graphql_guy',
      bio: 'API specialist',
      questionsCount: 13,
      answersCount: 66,
      reputation: 1510,
    },
    {
      id: '14',
      username: 'vue_veteran',
      bio: 'Vue.js for life',
      questionsCount: 9,
      answersCount: 88,
      reputation: 1388,
    },
    {
      id: '15',
      username: 'docker_dude',
      bio: 'Container evangelist',
      questionsCount: 10,
      answersCount: 77,
      reputation: 1620,
    },
    {
      id: '16',
      username: 'firebase_fan',
      bio: 'Real-time DB enjoyer',
      questionsCount: 18,
      answersCount: 64,
      reputation: 1440,
    },
    {
      id: '17',
      username: 'tailwind_tech',
      bio: 'Utility-first enthusiast',
      questionsCount: 7,
      answersCount: 40,
      reputation: 910,
    },
    {
      id: '18',
      username: 'payment_pro',
      bio: 'Stripe integration expert',
      questionsCount: 8,
      answersCount: 61,
      reputation: 1345,
    },
    {
      id: '19',
      username: 'orm_obsessed',
      bio: 'Prisma + SQL lover',
      questionsCount: 15,
      answersCount: 47,
      reputation: 1205,
    },
    {
      id: '20',
      username: 'nextjs_navigator',
      bio: 'Next.js and SSR expert',
      questionsCount: 10,
      answersCount: 84,
      reputation: 1725,
    },
  ],
};
