import { HistoryItem, HistoryType } from './types';

export const mockHistoryData: HistoryItem[] = [
  {
    id: '1',
    type: HistoryType.QUESTION_CREATE,
    userId: 'user-1',
    contentTitle: 'Làm thế nào để tối ưu hóa performance React application?',
    questionId: 'q-1',
    createdAt: new Date('2024-01-15T10:30:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '2',
    type: HistoryType.ANSWER_CREATE,
    userId: 'user-1',
    contentTitle: 'Cách sử dụng useState và useEffect hiệu quả',
    questionId: 'q-2',
    createdAt: new Date('2024-01-14T14:20:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '3',
    type: HistoryType.COMMENT_CREATE,
    userId: 'user-1',
    contentTitle: 'Thêm comment về cách implement Redux Toolkit',
    questionId: 'q-3',
    createdAt: new Date('2024-01-13T09:15:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '4',
    type: HistoryType.QUESTION_VOTE,
    userId: 'user-1',
    contentTitle: 'Database indexing best practices',
    questionId: 'q-4',
    createdAt: new Date('2024-01-12T16:45:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '5',
    type: HistoryType.ANSWER_VOTE,
    userId: 'user-1',
    contentTitle: 'Giải thích về microservices architecture',
    questionId: 'q-5',
    createdAt: new Date('2024-01-11T11:30:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '6',
    type: HistoryType.QUESTION_EDIT,
    userId: 'user-1',
    contentTitle: 'Sửa đổi câu hỏi về Docker containerization',
    questionId: 'q-6',
    createdAt: new Date('2024-01-10T13:20:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '7',
    type: HistoryType.ANSWER_CHOSEN,
    userId: 'user-1',
    contentTitle: 'Chọn câu trả lời tốt nhất cho GraphQL vs REST API',
    questionId: 'q-7',
    createdAt: new Date('2024-01-09T15:10:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '8',
    type: HistoryType.COMMENT_VOTE,
    userId: 'user-1',
    contentTitle: 'Vote comment về JWT authentication',
    questionId: 'q-8',
    createdAt: new Date('2024-01-08T08:45:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '9',
    type: HistoryType.REPORT_CREATE,
    userId: 'user-1',
    contentTitle: 'Báo cáo nội dung spam về cryptocurrency',
    questionId: 'q-9',
    createdAt: new Date('2024-01-07T12:30:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '10',
    type: HistoryType.ANSWER_EDIT,
    userId: 'user-1',
    contentTitle: 'Chỉnh sửa câu trả lời về Next.js SSR',
    questionId: 'q-10',
    createdAt: new Date('2024-01-06T17:20:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '11',
    type: HistoryType.QUESTION_DOWNVOTE,
    userId: 'user-1',
    contentTitle: 'Downvote câu hỏi về Python basic syntax',
    questionId: 'q-11',
    createdAt: new Date('2024-01-05T14:15:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '12',
    type: HistoryType.QUESTION_CREATE,
    userId: 'user-1',
    contentTitle: 'Cách implement real-time chat với Socket.io',
    questionId: 'q-12',
    createdAt: new Date('2024-01-04T10:45:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '13',
    type: HistoryType.ANSWER_DELETE,
    userId: 'user-1',
    contentTitle: 'Xóa câu trả lời về MongoDB aggregation',
    questionId: 'q-13',
    createdAt: new Date('2024-01-03T09:30:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '14',
    type: HistoryType.COMMENT_EDIT,
    userId: 'user-1',
    contentTitle: 'Sửa comment về AWS deployment',
    questionId: 'q-14',
    createdAt: new Date('2024-01-02T16:00:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
  {
    id: '15',
    type: HistoryType.ANSWER_DOWNVOTE,
    userId: 'user-1',
    contentTitle: 'Downvote câu trả lời về TypeScript interfaces',
    questionId: 'q-15',
    createdAt: new Date('2024-01-01T11:20:00Z'),
    user: {
      id: 'user-1',
      username: 'nguyenvan_dev',
      profilePicture: 'https://i.pravatar.cc/40?img=1',
    },
  },
];
